Repository TheSwain/Fulpstation, pull requests merged in 2020-07, with the labels that each got.

#360 Ventcrawl Vision
  code/modules/atmospherics/machinery/atmosmachinery.dm
Labels: Balance

#411 Wintercoats, yet again.
  code/FulpstationCode/wintercoats.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/vending/wardrobes.dm
  icons/Fulpicons/Penguins_cove/Winter_Coat_Pile/wintercoat_lefthand.dmi
  icons/Fulpicons/Penguins_cove/Winter_Coat_Pile/wintercoat_righthand.dmi
  icons/Fulpicons/Penguins_cove/Winter_Coat_Pile/wintercoathoods.dmi
  icons/Fulpicons/Penguins_cove/Winter_Coat_Pile/wintercoats.dmi
  icons/Fulpicons/Penguins_cove/Winter_Coat_Pile/wintercoats_icons.dmi
Labels: Sprites

#395 [READY] T5 Laser Pointers
  code/game/objects/items/devices/laserpointer.dm
Labels: Balance, Ready

#348 [READY] Changes prototype station (Syndicate Engi Corps ghost role)
  _maps/RandomRuins/SpaceRuins/prototype.dmm
  code/FulpstationCode/fulpspaceruins.dm
Labels: Mapping, Stale

#356 [READY] General fix for Cybersun ship.
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/cybersun/cybersun.dm
  code/modules/ruins/spaceruin_code/forgottenship.dm
  tgstation.dme
Labels: Enhancement, Fix, Ready, Stale

#371 [TM] Adds new ruin on lavaland with ghost-role spawners.
  _maps/RandomRuins/LavaRuins/lavaland_surface_techcult.dmm
  code/modules/projectiles/guns/energy/sniper.dm
  code/modules/ruins/lavalandruin_code/techcult.dm
  code/zFulpstationCode/fulp_overwrite_vars.dm
  icons/Fulpicons/cards.dmi
  icons/Fulpicons/energy_sniper.dmi
  icons/Fulpicons/energy_sniper_l.dmi
  icons/Fulpicons/energy_sniper_r.dmi
  icons/Fulpicons/tier4_organs.dmi
  tgstation.dme
Labels: Features, Mapping, Stale, Work In Progress

#352 [READY] Adds Syndicate Jobs hud icons.
  code/FulpstationCode/fulp_integration.dm
  code/modules/jobs/access.dm
  icons/Fulpicons/fulphud.dmi
  icons/Fulpicons/fulphud_mirror.dmi
  icons/Fulpicons/icon_mirrors/hud_mirror.dmi
Labels: Features, Ready, Sprites
