Repository TheSwain/Fulpstation, pull requests merged in 2020-08, with the labels that each got.

#451 More barsigns
  code/game/objects/structures/barsigns.dm
  icons/obj/barsigns.dmi
Labels: Features

#439 English muffacka do you speak it
  code/modules/language/language_holder.dm
Labels: Features, Ready

#449 Cleans up all the warnings in the codebase, makes some minor changes to behavior
  code/FulpstationCode/dice_fulp.dm
  code/FulpstationCode/fulp_procs.dm
  code/FulpstationCode/sec_expanded_loadouts/detective_goggles.dm
  code/game/data_huds.dm
  code/game/gamemodes/bloodsucker/bloodsucker.dm
  code/game/world.dm
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
  code/modules/antagonists/bloodsucker/bloodsucker_powers.dm
  code/modules/antagonists/bloodsucker/bloodsucker_sunlight.dm
  code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
  code/modules/antagonists/bloodsucker/items/bloodsucker_items.dm
  code/modules/antagonists/bloodsucker/objects/bloodsucker_crypt.dm
  code/modules/antagonists/bloodsucker/powers/bs_feed.dm
  code/modules/antagonists/bloodsucker/powers/bs_haste.dm
  code/modules/antagonists/bloodsucker/powers/bs_veil.dm
  code/modules/antagonists/bloodsucker/powers/v_recuperate.dm
  code/modules/mentor_fulp/mentor.dm
  code/modules/mentor_fulp/mentor_bindings_fulp.dm
  code/modules/mob/living/carbon/human/species_types/beefmen.dm
  tgstation.dme
Labels: Fix

#422 Makes sleepy pen available to nuclear and clown operative uplinks.
  code/zFulpstationCode/fulp_overwrite_vars.dm
Labels: Features

#445 Heliostation and Boxstation Updates
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Heliostation/heliostation.dmm
  _maps/map_files/Heliostation/job_changes.dm
Labels: Fix

#432 Franklin
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species_types/beefmen.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
Labels: Enhancement, Fix

#454 Fix for Sec Radios
  code/FulpstationCode/fulp_starter_gear/fulp_starter_gear.dm
Labels: Fix

#392 [READY] Minebot Improvements and Upgrades
  code/modules/mining/machine_vending.dm
  code/modules/mining/minebot.dm
  code/modules/movespeed/modifiers/mobs.dm
Labels: Balance
