Repository TheSwain/Fulpstation, pull requests merged in 2020-06, with the labels that each got.

#344 Refactor create_random_mob
  code/__HELPERS/mobs.dm
Labels: Fix

#379 [READY] Heliostation: Engineering maint, HoP office, and small bug fixes.
  _maps/map_files/Heliostation/heliostation.dmm
  _maps/map_files/Heliostation/job_changes.dm
Labels: Enhancement, Mapping

#399 [READY] More Stuff In The Logs
  code/__HELPERS/files.dm
  code/__HELPERS/roundend.dm
  code/datums/ai_laws.dm
Labels: Enhancement

#408 Pet objectives attempt 2
  code/game/gamemodes/objective_items.dm
Labels: Balance, Enhancement

#396 New space ambience song
  code/__DEFINES/sound.dm
  sound/Fulpsounds/spacepad.ogg
Labels: Sound
