Repository TheSwain/Fulpstation, pull requests merged in 2020-02, with the labels that each got.

#229 Update for Body Cams
  code/FulpstationCode/body_camera_files/body_camera_procs.dm
  code/FulpstationCode/improved_record_security/fulp_improved_record_security.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  code/zFulpstationCode/fulp_overwrite_vars.dm
Labels: Stale, enhancement, ready

#230 limit mech sets by manipulator tier
  code/game/mecha/mech_fabricator.dm
Labels: ready

#234 Reverting chat color for dark mode
  code/modules/goonchat/browserassets/css/browserOutput.css
Labels: Stale, ready

#235 Minor Holobed Tweak
  code/FulpstationCode/medborg_holobed/medborg_holobed.dm
Labels: Stale, ready

#239 Engiborg Electroadaptive Pseudocircuit Now Works With Airlocks
  code/FulpstationCode/fulp_airlock_electroadaptive/fulp_airlock_electroadaptive_procs.dm
  code/game/objects/items/devices/electroadaptive_pseudocircuit.dm
  code/game/objects/structures/door_assembly.dm
  code/zFulpstationCode/fulp_overwrite_vars.dm
  tgstation.dme
Labels: Stale, ready

#242 Tweak for Borg Radio PR
  code/FulpstationCode/borg_radio_files/borg_radio.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/zFulpstationCode/fulp_overwrite_vars.dm
Labels: Stale, ready

#243 Enable Night Shifts
  config/game_options.txt
Labels: Stale, ready

#244 Remove Intergalactic Common from Ash Walkers
  code/modules/language/language_holder.dm
Labels: Stale

#251 fix mesmerize targetting heart for some reason
  code/modules/antagonists/bloodsucker/powers/bs_mesmerize.dm
Labels: ready

#253 Sec Borg Additions and Upgrades
  code/FulpstationCode/sec_borg_files/fulp_sec_borg.dm
  code/game/machinery/computer/camera.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/zFulpstationCode/fulp_overwrite_vars.dm
  tgstation.dme
Labels: Stale

#268 Electroadaptive Psuedocircuit Tweak
  code/FulpstationCode/fulp_airlock_electroadaptive/fulp_airlock_electroadaptive_procs.dm
  code/game/objects/items/devices/electroadaptive_pseudocircuit.dm
  code/game/objects/structures/windoor_assembly.dm
  code/zFulpstationCode/fulp_overwrite_vars.dm
Labels: ready

#263 Cleans up icon updating for medborg organ bags
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Labels: ready

#232 Space DnD for HomingPenguin
  _maps/RandomRuins/SpaceRuins/DnDmansion.dmm
  code/FulpstationCode/fulpspaceruins.dm
Labels: Stale, enhancement

#265 Engiborg Basic Manipulator and Upgrade Added
  code/FulpstationCode/fulp_cyborgs/cyborg_upgrades.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/zFulpstationCode/fulp_overwrite_vars.dm
  tgstation.dme
Labels: ready
