Repository TheSwain/Fulpstation, pull requests merged in 2020-05, with the labels that each got.

#333 tweak the way phobetor tears are made
  code/FulpstationCode/fulp_procs.dm
Labels: performance

#325 5*3=15, not 30
  code/FulpstationCode/t5_parts.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/vehicles/motorized_wheelchair.dm
Labels: Fix

#342 Steal pets as traitor objectives
  code/game/gamemodes/objective_items.dm
Labels: Features, Ready

#322 Borg Chameleon Projector Improvement Patch
  code/FulpstationCode/fulp_medborg/fulp_medborg_updates.dm
  code/FulpstationCode/fulp_syndiborg_files/fulp_syndicate_medborg.dm
  code/FulpstationCode/sec_borg_files/fulp_sec_borg.dm
  code/modules/antagonists/nukeop/equipment/borgchameleon.dm
  code/modules/research/techweb/all_nodes.dm
  code/zFulpstationCode/fulp_overwrite_vars.dm
Labels: Features, Ready

#301 Plasmaman gloves
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
Labels: Balance, Ready

#343 Minor Bugfix for Loading Organs Into Smartfridge Via Medborg Bag
  code/FulpstationCode/fulp_medborg/fulp_medborg_updates.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Labels: Fix

#354 Add Heliostation (Working title)
  _maps/heliostation.json
  _maps/map_files/Heliostation/heliostation.dmm
  _maps/shuttles/emergency_news.dmm
  code/game/turfs/open/floor/mineral_floor.dm
  config/maps.txt
  icons/turf/floors.dmi
Labels: Features, Mapping, Waiting For Feedback

#361 Fixes DnD. finally
  _maps/RandomRuins/SpaceRuins/DnDmansion.dmm
  code/FulpstationCode/fulpspaceruins.dm
Labels: Fix
